name: Run Simulation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
    - name: Result
      run: ls -la
    - name: Clone graphwalker-report
      uses: actions/checkout@v4
      with:
        repository: prmiguel/graphwalker-report
        path: graphwalker-report
    - name: Generate Report
      run: |
        cd ./graphwalker-report
        source replace_graph_data.sh $GITHUB_WORKSPACE/FullEdgeCoverageTest.json
        ls -la
